---
  - name: ensure directory /spacen/fastdfs is present
    file: state=directory path={{item}} owner=www-data group=www-data
    with_items:
      - /space1/fastdfs
      - /space2/fastdfs
      - /space3/fastdfs
      - /space4/fastdfs
    tags: fastdfs
    
  - name: copy fastdfs deb
    copy: src={{fastdfsdeb}} dest=/tmp/{{fastdfsdeb}}
    tags: fastdfs

  - name: install fastdfs deb
    command: /usr/bin/dpkg -i /tmp/{{fastdfsdeb}}
    tags: fastdfs

  - name: copy fastdfs nginx deb
    copy: src={{nginxfdfsdeb}} dest=/tmp/{{nginxfdfsdeb}}
    tags: fastdfs

  - name: install fastdfs nginx deb
    command: /usr/bin/dpkg -i /tmp/{{nginxfdfsdeb}}
    tags: fastdfs

  - name: copy fastdfs php deb
    copy: src={{phpfdfsdeb}} dest=/tmp/{{phpfdfsdeb}}
    tags: fastdfs

  - name: install fastdfs php deb
    command: /usr/bin/dpkg -i /tmp/{{phpfdfsdeb}}
    tags: fastdfs

  - name: copy fastdfs python deb
    copy: src={{pyfdfsdeb}} dest=/tmp/{{pyfdfsdeb}}
    tags: fastdfs

  - name: install fastdfs python deb
    command: /usr/bin/dpkg -i /tmp/{{pyfdfsdeb}}
    tags: fastdfs

  - name: copy startup files
    copy: src={{item}} dest=/etc/init.d mode=0644
    with_items:
      - fdfs_storaged
      - fdfs_trackerd
      - nginx
    tags: fastdfs

  - name: copy nginx config
    copy: src={{item}} dest=/etc/nginx mode=0644
    with_items:
      - nginx.conf
      - mime.types
    tags: fastdfs

  - name: copy fastdfs config
    copy: src={{item}} dest=/etc/fdfs mode=0644
    with_items:
      - tracker.conf
      - http.conf
    tags: fastdfs

  - name: copy fastdfs config
    template: src=client.conf.j2 dest=/etc/fdfs/client.conf mode=0644
    tags: fastdfs
    
  - name: copy fastdfs config
    template: src=storage.conf.j2 dest=/etc/fdfs/storage.conf mode=0644
    tags: fastdfs
    
  - name: copy fastdfs config
    template: src=mod_fastdfs.conf.j2 dest=/etc/fdfs/mod_fastdfs.conf mode=0644
    tags: fastdfs
    
  - name: ensure directory sistes is present
    file: state=directory path={{item}}
    with_items:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
      - /var/log/nginx
    tags: fastdfs

  - name: copy fastdfs nginx config
    template: src=tracker-nginx.conf.j2 dest=/etc/nginx/sites-available/tracker-nginx.conf mode=0644
    tags: fastdfs

  - name: copy fastdfs nginx config
    copy: src=storage-nginx.conf dest=/etc/nginx/sites-available/ mode=0644
    tags: fastdfs
    
  - name: link to site-enabled
    file: src=/etc/nginx/sites-available/storage-nginx.conf dest=/etc/nginx/sites-enabled/storage-nginx.conf state=link
    tags: fastdfs
    
  - name: link to site-enabled
    file: src=/etc/nginx/sites-available/tracker-nginx.conf dest=/etc/nginx/sites-enabled/tracker-nginx.conf state=link
    tags: fastdfs

  - name: reload nginx service
    service: name={{item}} state=started
    with_items:
      - nginx
      - fdfs_storaged
      - fdfs_trackerd
    tags: fastdfs

  - name: copy monit configuration
    copy: src={{item}} dest=/etc/monit/conf.d/
    with_items:
      - check-nginx
      - check-fdfs-storage
      - check-fdfs-tracker
    tags: fastdfs
    
  - name: reload monit resource
    service: name=monit state=reloaded
    tags: fastdfs
    
