---
- hosts: all

  user: $user
  sudo: true

  roles:
    - common
    - ssh
    - mysql
    - nginx-php
    - oh-my-zsh
    - java
    - redis
    - thrift
    - buildredis
    - buildthrift
    - buildfastdfs
    - python
    - user
    - tizi
    - waijiao
    - aliyun
    - phone
    - ppp
    - pptpd

