---
  - name: install python pip
    apt: package=python-pip
    tags: thrift
    
  - name: copy thrift deb
    copy: src={{thriftdeb}} dest=/tmp/{{thriftdeb}}
    tags: thrift

  - name: install thrift deb
    command: /usr/bin/dpkg -i /tmp/{{thriftdeb}}
    tags: thrift

  - name: install python thrift
    pip: name=thrift
    tags: thrift
