---
  - name: install python pip (apt)
    apt: package=python-pip
    tags: thrift
    when: "ansible_pkg_mgr == 'apt'"

  - name: install python pip (yum)
    yum: package=python-pip
    tags: thrift
    when: "ansible_pkg_mgr == 'yum'"    
    
  - name: copy thrift deb
    copy: src={{thriftdeb}} dest=/tmp/{{thriftdeb}}
    tags: thrift

  - name: install thrift deb
    command: /usr/bin/dpkg -i /tmp/{{thriftdeb}}
    tags: thrift

  - name: install python thrift
    pip: name=thrift
    tags: thrift
