---
  - name: Install base python packages
    apt: pkg={{item}}
    with_items:
      - python-pip
      - python-mysqldb
    tags: python

  - name: pip install packages
    pip: name={{item}}
    with_items:
      - sqlalchemy
      - redis
      - python-gflags
      - daemon
      - thrift
    tags: python

