---
  - name: Install zsh (apt)
    apt: pkg=zsh
    tags: zsh
    when: "ansible_pkg_mgr == 'apt'"

  - name: Install zsh (yum)
    yum: pkg=zsh
    tags: zsh
    when: "ansible_pkg_mgr == 'yum'"

  - name: Install oh-my-zsh
    sudo: False
    action: git repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
    tags: zsh

  - name: Creating new ~/.zshrc
    sudo: False
    action: shell cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
    tags: zsh

  - name: modify ~/.zshrc
    sudo: False
    action: shell sed -i -e 's/plugins=(git)/plugins=\(git history-substring-search\)/' ~/.zshrc
    tags: zsh

  - name: modify ~/.zshrc
    sudo: False
    action: shell sed -i -e '$ a\export EDITOR=vim\nalias ack="ack-grep"' ~/.zshrc
    tags: zsh

  - name: Set zsh as default shell
    user: name=$user shell=/bin/zsh
    tags: zsh
    
  - name: Installing spf13-vim, The Ultimate Vim Distribution (http://vim.spf13.com)
    sudo: False
    action: shell curl https://j.mp/spf13-vim3 -L -o - | sh
    tags: vim

