---
  #- name: git checkout source code
  #  git: repo=git@192.168.11.11:liuhua/php_91tizi.git dest=/usr/share/nginx/tizi

  - name: copy files
    copy: src=tizi.tar.gz dest=~/tizi.tar.gz

  - name: extract files
    command: tar zxf tizi.tar.gz chdir=~

  - name: rsync all files into dest
    command: rsync -avz --progress --delete --exclude="*.pyc" ./tizi /usr/share/nginx/ chdir=~
  
  - name: copy tizi nginx configurations
    copy: src=tizi.com dest=/etc/nginx/sites-available/tizi.com

  - name: link to site-enabled
    file: src=/etc/nginx/sites-available/tizi.com dest=/etc/nginx/sites-enabled/tizi.com state=link

  - name: reload nginx
    service: name=nginx state=reloaded

