---
  - name: Install nginx
    apt: pkg=nginx

  - name: update nginx configuration
    copy: src=nginx.conf dest=/etc/nginx/nginx.conf
    
  - name: update nginx configuration(default)
    copy: src=nginx-default dest=/etc/nginx/sites-available/default
    
  - name: Install mysql
    apt: pkg={{item}}
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
      
  - name: update mysql configuration
    copy: src=my.cnf dest=/etc/mysql/my.cnf
    
  - name: Install php-fpm
    apt: pkg={{item}}
    with_items:
      - php5-fpm
      - php5-dev
      - php5-cli
      - php-pear

  - name: restart all services
    service: name={{item}} state=restarted
    with_items:
      - php5-fpm
      - nginx
      - mysql

  - name: copy monit configuration
    copy: src={{item}} dest=/etc/monit/conf.d/
    with_items:
      - check-mysql
      - check-nginx
      - check-phpfpm

  - name: reload monit resource
    service: name=monit state=reloaded

