---
  - name: Install nginx
    apt: pkg=nginx

  - name: Install mysql
    apt: pkg={{item}}
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb

  - name: Install php-fpm
    apt: pkg={{item}}
    with_items:
      - php5-fpm
      - php5-dev
      - php5-cli
      - php-pear

  - name: start all services
    service: name={{item}} state=started
    with_items:
      - php5-fpm
      - nginx
      - mysql

