---
  #- name: set hostname
  #  command: echo "{{hostname}}" > /etc/hostname && hostname -F /etc/hostname

  #- name: set hosts
  #  template: src=hosts.j2 dest=/etc/hosts

  - name: set timezone
    command: echo "Asia/Shanghai" > /etc/timezone && dpkg-reconfigure -f noninteractive tzdata

  - name: set locale to en_us
    copy: src=locale dest=/etc/default/locale

  - name: reconfigure locales
    command: dpkg-reconfigure -f noninteractive locales
    
  - name: update sources.list
    template: src=sources.list.j2 dest=/etc/apt/sources.list backup=yes

  - name: Upgrade apt packages
    apt: upgrade=yes
         update_cache=yes

  #- name: upgrade virtualbox guest if needed
  #  apt: pkg=virtualbox-guest-utils

  - name: creating a firewall, copy iptables.firewall.rules
    copy: src=iptables.firewall.rules dest=/etc/iptables.firewall.rules

  - name: creating a firewall, copy firewall
    copy: src=firewall dest=/etc/network/if-pre-up.d/firewall mode=755

  - name: apply firewall rules
    command: /etc/network/if-pre-up.d/firewall

  - name: Install common tools (git vim ntp curl tmux ack most ncdu unzip monit fail2ban)
    apt: pkg={{item}}
    with_items:
       - git
       - vim
       - ntp
       - curl
       - tmux
       - ack-grep
       - most
       - ncdu
       - unzip
       - monit
       - fail2ban

  - name: copy tumx config
    sudo: False
    copy: src=.tmux.conf dest=~/.tmux.conf
    
  - name: copy monit configuration
    copy: src=monitrc dest=/etc/monit/monitrc
    tags: monit
       
  - name: start monit service
    service: name=monit state=reloaded
    tags: monit

